[package]
name = "nearmint_nft"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[[target.starknet-contract]]
sierra = true
casm = true
# Optimizaciones para compilación más rápida
sierra-replace-ids = true
allowed-libfuncs-list = { name = "experimental" }

[lib]

[tool.snforge]
# Configuración para tests más rápidos
exit_first = true

[tool.scarb]
# Configuración de compilación optimizada
[tool.scarb.build]
parallel = true
